# Generated by Django 5.2.3 on 2025-06-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_attendance_status_attendance_time_studentprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
    ]
