# Generated by Django 5.2.3 on 2025-06-30 18:18

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_attendance_status_attendance_is_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.ImageField(upload_to=main.models.face_image_upload_path),
        ),
    ]
