# Generated by Django 5.2.3 on 2025-07-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_face_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
