# Generated by Django 5.2.3 on 2025-08-02 15:38

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['registration_number']},
        ),
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.face_image_upload_path),
        ),
    ]
