# Generated by Django 5.2.3 on 2025-09-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_student_options_alter_student_face_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
